// Code generated by cmd/generate; DO NOT EDIT.

package acp

import "context"

// Agent defines the agent-side RPC interface.
type Agent interface {
	// Request parameters for the authenticate method.
	//
	// Specifies which authentication method to use.
	Authenticate(ctx context.Context, params AuthenticateRequest) (AuthenticateResponse, error)
	// Request parameters for the initialize method.
	//
	// Sent by the client to establish connection and negotiate capabilities.
	//
	// See protocol docs: [Initialization](https://agentclientprotocol.com/protocol/initialization)
	Initialize(ctx context.Context, params InitializeRequest) (InitializeResponse, error)
	// Notification to cancel ongoing operations for a session.
	//
	// See protocol docs: [Cancellation](https://agentclientprotocol.com/protocol/prompt-turn#cancellation)
	SessionCancel(ctx context.Context, params CancelNotification) error
	// Request parameters for listing existing sessions.
	//
	// Only available if the Agent supports the `sessionCapabilities.list` capability.
	ListSessions(ctx context.Context, params ListSessionsRequest) (ListSessionsResponse, error)
	// Request parameters for loading an existing session.
	//
	// Only available if the Agent supports the `loadSession` capability.
	//
	// See protocol docs: [Loading Sessions](https://agentclientprotocol.com/protocol/session-setup#loading-sessions)
	LoadSession(ctx context.Context, params LoadSessionRequest) (LoadSessionResponse, error)
	// Request parameters for creating a new session.
	//
	// See protocol docs: [Creating a Session](https://agentclientprotocol.com/protocol/session-setup#creating-a-session)
	NewSession(ctx context.Context, params NewSessionRequest) (NewSessionResponse, error)
	// Request parameters for sending a user prompt to the agent.
	//
	// Contains the user's message and any additional context.
	//
	// See protocol docs: [User Message](https://agentclientprotocol.com/protocol/prompt-turn#1-user-message)
	Prompt(ctx context.Context, params PromptRequest) (PromptResponse, error)
	// Request parameters for setting a session configuration option.
	SetSessionConfigOption(ctx context.Context, params SetSessionConfigOptionRequest) (SetSessionConfigOptionResponse, error)
	// Request parameters for setting a session mode.
	SetSessionMode(ctx context.Context, params SetSessionModeRequest) (SetSessionModeResponse, error)
}

// Agent method wire names.
const (
	MethodAgentAuthenticate           = "authenticate"
	MethodAgentInitialize             = "initialize"
	MethodAgentSessionCancel          = "session/cancel"
	MethodAgentListSessions           = "session/list"
	MethodAgentLoadSession            = "session/load"
	MethodAgentNewSession             = "session/new"
	MethodAgentPrompt                 = "session/prompt"
	MethodAgentSetSessionConfigOption = "session/set_config_option"
	MethodAgentSetSessionMode         = "session/set_mode"
)
