// Code generated by cmd/generate; DO NOT EDIT.

package acp

import "context"

// Agent defines the agent-side RPC interface.
type Agent interface {
	// Request parameters for the authenticate method.
	//
	// Specifies which authentication method to use.
	Authenticate(ctx context.Context, params AuthenticateRequest) (AuthenticateResponse, error)
	// Notification sent when a file is edited.
	DocumentDidChange(ctx context.Context, params DidChangeDocumentNotification) error
	// Notification sent when a file is closed.
	DocumentDidClose(ctx context.Context, params DidCloseDocumentNotification) error
	// Notification sent when a file becomes the active editor tab.
	DocumentDidFocus(ctx context.Context, params DidFocusDocumentNotification) error
	// Notification sent when a file is opened in the editor.
	DocumentDidOpen(ctx context.Context, params DidOpenDocumentNotification) error
	// Notification sent when a file is saved.
	DocumentDidSave(ctx context.Context, params DidSaveDocumentNotification) error
	// Request parameters for the initialize method.
	//
	// Sent by the client to establish connection and negotiate capabilities.
	//
	// See protocol docs: [Initialization](https://agentclientprotocol.com/protocol/initialization)
	Initialize(ctx context.Context, params InitializeRequest) (InitializeResponse, error)
	// Request parameters for the logout method.
	//
	// Terminates the current authenticated session.
	Logout(ctx context.Context, params LogoutRequest) (LogoutResponse, error)
	// **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Notification parameters for `mcp/message`.
	//
	// This is used when the wrapped MCP message is a notification and the outer JSON-RPC
	// envelope has no `id`.
	UnstableMCPMessage(ctx context.Context, params MessageMCPNotification) error
	// Notification sent when a suggestion is accepted.
	NesAccept(ctx context.Context, params AcceptNesNotification) error
	// Request to close an NES session.
	//
	// The agent **must** cancel any ongoing work related to the NES session
	// and then free up any resources associated with the session.
	CloseNes(ctx context.Context, params CloseNesRequest) (CloseNesResponse, error)
	// Notification sent when a suggestion is rejected.
	NesReject(ctx context.Context, params RejectNesNotification) error
	// Request to start an NES session.
	StartNes(ctx context.Context, params StartNesRequest) (StartNesResponse, error)
	// Request for a code suggestion.
	SuggestNes(ctx context.Context, params SuggestNesRequest) (SuggestNesResponse, error)
	// **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Request parameters for `providers/disable`.
	UnstableDisableProvider(ctx context.Context, params DisableProviderRequest) (DisableProviderResponse, error)
	// **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Request parameters for `providers/list`.
	UnstableListProviders(ctx context.Context, params ListProvidersRequest) (ListProvidersResponse, error)
	// **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Request parameters for `providers/set`.
	//
	// Replaces the full configuration for one provider id.
	UnstableSetProvider(ctx context.Context, params SetProviderRequest) (SetProviderResponse, error)
	// Notification to cancel ongoing operations for a session.
	//
	// See protocol docs: [Cancellation](https://agentclientprotocol.com/protocol/prompt-turn#cancellation)
	SessionCancel(ctx context.Context, params CancelNotification) error
	// Request parameters for closing an active session.
	//
	// If supported, the agent **must** cancel any ongoing work related to the session
	// (treat it as if `session/cancel` was called) and then free up any resources
	// associated with the session.
	//
	// Only available if the Agent supports the `session.close` capability.
	CloseSession(ctx context.Context, params CloseSessionRequest) (CloseSessionResponse, error)
	// Request parameters for deleting an existing session from `session/list`.
	//
	// Only available if the Agent supports the `session.delete` capability.
	DeleteSession(ctx context.Context, params DeleteSessionRequest) (DeleteSessionResponse, error)
	// **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Request parameters for forking an existing session.
	//
	// Creates a new session based on the context of an existing one, allowing
	// operations like generating summaries without affecting the original session's history.
	//
	// Only available if the Agent supports the `session.fork` capability.
	UnstableForkSession(ctx context.Context, params ForkSessionRequest) (ForkSessionResponse, error)
	// Request parameters for listing existing sessions.
	//
	// Only available if the Agent supports the `session.list` capability.
	ListSessions(ctx context.Context, params ListSessionsRequest) (ListSessionsResponse, error)
	// Request parameters for loading an existing session.
	//
	// Only available if the Agent supports the `session.load` capability.
	//
	// See protocol docs: [Loading Sessions](https://agentclientprotocol.com/protocol/session-setup#loading-sessions)
	LoadSession(ctx context.Context, params LoadSessionRequest) (LoadSessionResponse, error)
	// Request parameters for creating a new session.
	//
	// See protocol docs: [Creating a Session](https://agentclientprotocol.com/protocol/session-setup#creating-a-session)
	NewSession(ctx context.Context, params NewSessionRequest) (NewSessionResponse, error)
	// Request parameters for sending a user prompt to the agent.
	//
	// Contains the user's message and any additional context.
	//
	// See protocol docs: [User Message](https://agentclientprotocol.com/protocol/prompt-turn#1-user-message)
	Prompt(ctx context.Context, params PromptRequest) (PromptResponse, error)
	// Request parameters for resuming an existing session.
	//
	// Resumes an existing session without returning previous messages (unlike `session/load`).
	// This is useful for agents that can resume sessions but don't implement full session loading.
	//
	// Only available if the Agent supports the `session.resume` capability.
	ResumeSession(ctx context.Context, params ResumeSessionRequest) (ResumeSessionResponse, error)
	// Request parameters for setting a session configuration option.
	SetSessionConfigOption(ctx context.Context, params SetSessionConfigOptionRequest) (SetSessionConfigOptionResponse, error)
}

// Agent method wire names.
const (
	MethodAgentAuthenticate            = "authenticate"
	MethodAgentDocumentDidChange       = "document/didChange"
	MethodAgentDocumentDidClose        = "document/didClose"
	MethodAgentDocumentDidFocus        = "document/didFocus"
	MethodAgentDocumentDidOpen         = "document/didOpen"
	MethodAgentDocumentDidSave         = "document/didSave"
	MethodAgentInitialize              = "initialize"
	MethodAgentLogout                  = "logout"
	MethodAgentUnstableMCPMessage      = "mcp/message"
	MethodAgentNesAccept               = "nes/accept"
	MethodAgentCloseNes                = "nes/close"
	MethodAgentNesReject               = "nes/reject"
	MethodAgentStartNes                = "nes/start"
	MethodAgentSuggestNes              = "nes/suggest"
	MethodAgentUnstableDisableProvider = "providers/disable"
	MethodAgentUnstableListProviders   = "providers/list"
	MethodAgentUnstableSetProvider     = "providers/set"
	MethodAgentSessionCancel           = "session/cancel"
	MethodAgentCloseSession            = "session/close"
	MethodAgentDeleteSession           = "session/delete"
	MethodAgentUnstableForkSession     = "session/fork"
	MethodAgentListSessions            = "session/list"
	MethodAgentLoadSession             = "session/load"
	MethodAgentNewSession              = "session/new"
	MethodAgentPrompt                  = "session/prompt"
	MethodAgentResumeSession           = "session/resume"
	MethodAgentSetSessionConfigOption  = "session/set_config_option"
)
