// Code generated by cmd/generate; DO NOT EDIT.

package acp

import (
	"context"
	"fmt"
)

func methodNotSupported(method string) *RPCError {
	return ErrMethodNotFound(method)
}

func notificationNotImplemented(method string) error {
	return fmt.Errorf("notification handler not implemented: %s", method)
}

// BaseAgent provides strict default implementations for the Agent interface.
//
// All request-style methods return method-not-found by default so missing
// capabilities fail loudly instead of silently succeeding with empty results.
// Notification-style methods return explicit errors so missing protocol hooks do
// not silently disappear during integration.
type BaseAgent struct{}

func (BaseAgent) LoginAuth(context.Context, LoginAuthRequest) (LoginAuthResponse, error) {
	return LoginAuthResponse{}, methodNotSupported(MethodAgentLoginAuth)
}

func (BaseAgent) LogoutAuth(context.Context, LogoutAuthRequest) (LogoutAuthResponse, error) {
	return LogoutAuthResponse{}, methodNotSupported(MethodAgentLogoutAuth)
}

func (BaseAgent) DocumentDidChange(context.Context, DidChangeDocumentNotification) error {
	return notificationNotImplemented(MethodAgentDocumentDidChange)
}

func (BaseAgent) DocumentDidClose(context.Context, DidCloseDocumentNotification) error {
	return notificationNotImplemented(MethodAgentDocumentDidClose)
}

func (BaseAgent) DocumentDidFocus(context.Context, DidFocusDocumentNotification) error {
	return notificationNotImplemented(MethodAgentDocumentDidFocus)
}

func (BaseAgent) DocumentDidOpen(context.Context, DidOpenDocumentNotification) error {
	return notificationNotImplemented(MethodAgentDocumentDidOpen)
}

func (BaseAgent) DocumentDidSave(context.Context, DidSaveDocumentNotification) error {
	return notificationNotImplemented(MethodAgentDocumentDidSave)
}

func (BaseAgent) Initialize(context.Context, InitializeRequest) (InitializeResponse, error) {
	return InitializeResponse{}, methodNotSupported(MethodAgentInitialize)
}

func (BaseAgent) UnstableMCPMessage(context.Context, MessageMCPRequest) (MessageMCPResponse, error) {
	return MessageMCPResponse{}, methodNotSupported(MethodAgentUnstableMCPMessage)
}

func (BaseAgent) UnstableMCPMessageNotification(context.Context, MessageMCPNotification) error {
	return notificationNotImplemented(MethodAgentUnstableMCPMessageNotification)
}

func (BaseAgent) NesAccept(context.Context, AcceptNesNotification) error {
	return notificationNotImplemented(MethodAgentNesAccept)
}

func (BaseAgent) CloseNes(context.Context, CloseNesRequest) (CloseNesResponse, error) {
	return CloseNesResponse{}, methodNotSupported(MethodAgentCloseNes)
}

func (BaseAgent) NesReject(context.Context, RejectNesNotification) error {
	return notificationNotImplemented(MethodAgentNesReject)
}

func (BaseAgent) StartNes(context.Context, StartNesRequest) (StartNesResponse, error) {
	return StartNesResponse{}, methodNotSupported(MethodAgentStartNes)
}

func (BaseAgent) SuggestNes(context.Context, SuggestNesRequest) (SuggestNesResponse, error) {
	return SuggestNesResponse{}, methodNotSupported(MethodAgentSuggestNes)
}

func (BaseAgent) UnstableDisableProvider(context.Context, DisableProviderRequest) (DisableProviderResponse, error) {
	return DisableProviderResponse{}, methodNotSupported(MethodAgentUnstableDisableProvider)
}

func (BaseAgent) UnstableListProviders(context.Context, ListProvidersRequest) (ListProvidersResponse, error) {
	return ListProvidersResponse{}, methodNotSupported(MethodAgentUnstableListProviders)
}

func (BaseAgent) UnstableSetProvider(context.Context, SetProviderRequest) (SetProviderResponse, error) {
	return SetProviderResponse{}, methodNotSupported(MethodAgentUnstableSetProvider)
}

func (BaseAgent) SessionCancel(context.Context, CancelNotification) error {
	return notificationNotImplemented(MethodAgentSessionCancel)
}

func (BaseAgent) CloseSession(context.Context, CloseSessionRequest) (CloseSessionResponse, error) {
	return CloseSessionResponse{}, methodNotSupported(MethodAgentCloseSession)
}

func (BaseAgent) DeleteSession(context.Context, DeleteSessionRequest) (DeleteSessionResponse, error) {
	return DeleteSessionResponse{}, methodNotSupported(MethodAgentDeleteSession)
}

func (BaseAgent) UnstableForkSession(context.Context, ForkSessionRequest) (ForkSessionResponse, error) {
	return ForkSessionResponse{}, methodNotSupported(MethodAgentUnstableForkSession)
}

func (BaseAgent) ListSessions(context.Context, ListSessionsRequest) (ListSessionsResponse, error) {
	return ListSessionsResponse{}, methodNotSupported(MethodAgentListSessions)
}

func (BaseAgent) LoadSession(context.Context, LoadSessionRequest) (LoadSessionResponse, error) {
	return LoadSessionResponse{}, methodNotSupported(MethodAgentLoadSession)
}

func (BaseAgent) NewSession(context.Context, NewSessionRequest) (NewSessionResponse, error) {
	return NewSessionResponse{}, methodNotSupported(MethodAgentNewSession)
}

func (BaseAgent) Prompt(context.Context, PromptRequest) (PromptResponse, error) {
	return PromptResponse{}, methodNotSupported(MethodAgentPrompt)
}

func (BaseAgent) ResumeSession(context.Context, ResumeSessionRequest) (ResumeSessionResponse, error) {
	return ResumeSessionResponse{}, methodNotSupported(MethodAgentResumeSession)
}

func (BaseAgent) SetSessionConfigOption(context.Context, SetSessionConfigOptionRequest) (SetSessionConfigOptionResponse, error) {
	return SetSessionConfigOptionResponse{}, methodNotSupported(MethodAgentSetSessionConfigOption)
}

var _ Agent = BaseAgent{}

// BaseClient provides strict default implementations for the Client interface.
//
// Request-style methods return method-not-found by default so client capability
// mismatches are explicit. SessionUpdate also reports an explicit error so UI
// state notifications do not silently disappear when the embedding client has
// not wired the callback yet.
type BaseClient struct{}

func (BaseClient) UnstableElicitationComplete(context.Context, CompleteElicitationNotification) error {
	return notificationNotImplemented(MethodClientUnstableElicitationComplete)
}

func (BaseClient) UnstableCreateElicitation(context.Context, CreateElicitationRequest) (CreateElicitationResponse, error) {
	return CreateElicitationResponse{}, methodNotSupported(MethodClientUnstableCreateElicitation)
}

func (BaseClient) UnstableConnectMCP(context.Context, ConnectMCPRequest) (ConnectMCPResponse, error) {
	return ConnectMCPResponse{}, methodNotSupported(MethodClientUnstableConnectMCP)
}

func (BaseClient) UnstableDisconnectMCP(context.Context, DisconnectMCPRequest) (DisconnectMCPResponse, error) {
	return DisconnectMCPResponse{}, methodNotSupported(MethodClientUnstableDisconnectMCP)
}

func (BaseClient) UnstableMCPMessage(context.Context, MessageMCPRequest) (MessageMCPResponse, error) {
	return MessageMCPResponse{}, methodNotSupported(MethodClientUnstableMCPMessage)
}

func (BaseClient) UnstableMCPMessageNotification(context.Context, MessageMCPNotification) error {
	return notificationNotImplemented(MethodClientUnstableMCPMessageNotification)
}

func (BaseClient) RequestPermission(context.Context, RequestPermissionRequest) (RequestPermissionResponse, error) {
	return RequestPermissionResponse{}, methodNotSupported(MethodClientRequestPermission)
}

func (BaseClient) SessionUpdate(context.Context, SessionNotification) error {
	return notificationNotImplemented(MethodClientSessionUpdate)
}

var _ Client = BaseClient{}
