// Code generated by cmd/generate; DO NOT EDIT.

package acp

import "context"

// Client defines the client-side RPC interface.
type Client interface {
	// **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Notification sent by the agent when a URL-based elicitation is complete.
	UnstableElicitationComplete(ctx context.Context, params CompleteElicitationNotification) error
	// **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Request from the agent to elicit structured user input.
	//
	// The agent sends this to the client to request information from the user,
	// either via a form or by directing them to a URL.
	// Elicitations are tied to a session (optionally a tool call) or a request.
	UnstableCreateElicitation(ctx context.Context, params CreateElicitationRequest) (CreateElicitationResponse, error)
	// **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Request parameters for `mcp/connect`.
	UnstableConnectMCP(ctx context.Context, params ConnectMCPRequest) (ConnectMCPResponse, error)
	// **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Request parameters for `mcp/disconnect`.
	UnstableDisconnectMCP(ctx context.Context, params DisconnectMCPRequest) (DisconnectMCPResponse, error)
	// **UNSTABLE**
	//
	// This capability is not part of the spec yet, and may be removed or changed at any point.
	//
	// Notification parameters for `mcp/message`.
	//
	// This is used when the wrapped MCP message is a notification and the outer JSON-RPC
	// envelope has no `id`.
	UnstableMCPMessage(ctx context.Context, params MessageMCPNotification) error
	// Request for user permission to execute a tool call.
	//
	// Sent when the agent needs authorization before performing a sensitive operation.
	//
	// See protocol docs: [Requesting Permission](https://agentclientprotocol.com/protocol/v2/draft/tool-calls#requesting-permission)
	RequestPermission(ctx context.Context, params RequestPermissionRequest) (RequestPermissionResponse, error)
	// Notification containing a session update from the agent.
	//
	// Used to stream real-time progress and results during prompt processing.
	//
	// See protocol docs: [Agent Reports Output](https://agentclientprotocol.com/protocol/v2/draft/prompt-lifecycle#3-agent-reports-output)
	SessionUpdate(ctx context.Context, params SessionNotification) error
}

// Client method wire names.
const (
	MethodClientUnstableElicitationComplete = "elicitation/complete"
	MethodClientUnstableCreateElicitation   = "elicitation/create"
	MethodClientUnstableConnectMCP          = "mcp/connect"
	MethodClientUnstableDisconnectMCP       = "mcp/disconnect"
	MethodClientUnstableMCPMessage          = "mcp/message"
	MethodClientRequestPermission           = "session/request_permission"
	MethodClientSessionUpdate               = "session/update"
)
