// Code generated by cmd/generate; DO NOT EDIT.

package acp

import "context"

// Client defines the client-side RPC interface.
type Client interface {
	// Request to read content from a text file.
	//
	// Only available if the client supports the `fs.readTextFile` capability.
	ReadTextFile(ctx context.Context, params ReadTextFileRequest) (ReadTextFileResponse, error)
	// Request to write content to a text file.
	//
	// Only available if the client supports the `fs.writeTextFile` capability.
	WriteTextFile(ctx context.Context, params WriteTextFileRequest) (WriteTextFileResponse, error)
	// Request for user permission to execute a tool call.
	//
	// Sent when the agent needs authorization before performing a sensitive operation.
	//
	// See protocol docs: [Requesting Permission](https://agentclientprotocol.com/protocol/tool-calls#requesting-permission)
	RequestPermission(ctx context.Context, params RequestPermissionRequest) (RequestPermissionResponse, error)
	// Notification containing a session update from the agent.
	//
	// Used to stream real-time progress and results during prompt processing.
	//
	// See protocol docs: [Agent Reports Output](https://agentclientprotocol.com/protocol/prompt-turn#3-agent-reports-output)
	SessionUpdate(ctx context.Context, params SessionNotification) error
	// Request to create a new terminal and execute a command.
	CreateTerminal(ctx context.Context, params CreateTerminalRequest) (CreateTerminalResponse, error)
	// Request to kill a terminal without releasing it.
	KillTerminal(ctx context.Context, params KillTerminalRequest) (KillTerminalResponse, error)
	// Request to get the current output and status of a terminal.
	TerminalOutput(ctx context.Context, params TerminalOutputRequest) (TerminalOutputResponse, error)
	// Request to release a terminal and free its resources.
	ReleaseTerminal(ctx context.Context, params ReleaseTerminalRequest) (ReleaseTerminalResponse, error)
	// Request to wait for a terminal command to exit.
	WaitForTerminalExit(ctx context.Context, params WaitForTerminalExitRequest) (WaitForTerminalExitResponse, error)
}

// Client method wire names.
const (
	MethodClientReadTextFile        = "fs/read_text_file"
	MethodClientWriteTextFile       = "fs/write_text_file"
	MethodClientRequestPermission   = "session/request_permission"
	MethodClientSessionUpdate       = "session/update"
	MethodClientCreateTerminal      = "terminal/create"
	MethodClientKillTerminal        = "terminal/kill"
	MethodClientTerminalOutput      = "terminal/output"
	MethodClientReleaseTerminal     = "terminal/release"
	MethodClientWaitForTerminalExit = "terminal/wait_for_exit"
)
