package main

import (
	"fmt"
	"sort"
	"strings"
)

// GenerateMethodMetadata produces methods_gen.go containing generated ACP
// method capability metadata.
func (g *Generator) GenerateMethodMetadata(pkg string) ([]byte, error) {
	methods := append(
		g.buildMethods(g.meta.AgentMethods, "agent"),
		g.buildMethods(g.meta.ClientMethods, "client")...,
	)
	sort.Slice(methods, func(i, j int) bool {
		return methods[i].WireMethod < methods[j].WireMethod
	})

	var buf strings.Builder
	buf.WriteString("// Code generated by cmd/generate; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg)
	buf.WriteString("var methodMetadata = map[string]Metadata{\n")
	for _, method := range methods {
		side := "SideAgent"
		if method.Side == "client" {
			side = "SideClient"
		}
		sessionCreating := method.Side == "agent" &&
			(method.WireMethod == "session/new" || method.WireMethod == "session/load")
		sessionBound := sessionCreating || g.methodHasRequiredProperty(method, "sessionId")
		sessionHeaderRequired := method.Side == "agent" && sessionBound && !sessionCreating

		fmt.Fprintf(&buf, "\t%q: {\n", method.WireMethod)
		fmt.Fprintf(&buf, "\t\tKey: %q,\n", method.Key)
		fmt.Fprintf(&buf, "\t\tWireMethod: %q,\n", method.WireMethod)
		fmt.Fprintf(&buf, "\t\tSide: %s,\n", side)
		fmt.Fprintf(&buf, "\t\tNotification: %t,\n", method.IsNotify)
		fmt.Fprintf(&buf, "\t\tSessionBound: %t,\n", sessionBound)
		fmt.Fprintf(&buf, "\t\tSessionHeaderRequired: %t,\n", sessionHeaderRequired)
		fmt.Fprintf(&buf, "\t\tSessionCreating: %t,\n", sessionCreating)
		fmt.Fprintf(&buf, "\t},\n")
	}
	buf.WriteString("}\n")

	return formatSource(buf.String())
}

func (g *Generator) methodHasRequiredProperty(method MethodInfo, property string) bool {
	if method.ReqType == "" {
		return false
	}
	schema, ok := g.schema.Defs[method.ReqType]
	if !ok || schema == nil {
		return false
	}
	for _, required := range schema.Required {
		if required == property {
			return true
		}
	}
	return false
}
