package main

import (
	"fmt"
	"strings"
)

// GenerateConnFiles produces three generated files for the conn package:
//   - agentOutbound: outbound methods on *AgentConnection (agent → client)
//   - clientOutbound: outbound methods on *ClientConnection (client → agent)
//   - handlers: handler registration functions for inbound dispatch
func (g *Generator) GenerateConnFiles(connPkg string) (agentOutbound, clientOutbound, handlers []byte, err error) {
	clientMethods := g.buildMethods(g.meta.ClientMethods, "client")
	agentMethods := g.buildMethods(g.meta.AgentMethods, "agent")

	agentOutbound, err = g.renderAgentOutbound(connPkg, clientMethods)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("agent outbound: %w", err)
	}

	clientOutbound, err = g.renderClientOutbound(connPkg, agentMethods)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("client outbound: %w", err)
	}

	handlers, err = g.renderHandlers(connPkg, agentMethods, clientMethods)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("handlers: %w", err)
	}

	return agentOutbound, clientOutbound, handlers, nil
}

// renderAgentOutbound generates outbound methods on AgentConnection.
// The agent sends to the client, so it uses Client-side method constants and types.
func (g *Generator) renderAgentOutbound(pkg string, clientMethods []MethodInfo) ([]byte, error) {
	var buf strings.Builder

	buf.WriteString("// Code generated by cmd/generate; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg)
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n\n")
	buf.WriteString("\tacp \"github.com/eino-contrib/acp\"\n")
	buf.WriteString("\t\"github.com/eino-contrib/acp/internal/jsonrpc\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("// --- Outbound: Agent sends to Client (generated) ---\n\n")

	for _, m := range clientMethods {
		constName := fmt.Sprintf("acp.MethodClient%s", m.GoName)
		if m.IsNotify {
			fmt.Fprintf(&buf, "func (a *AgentConnection) %s(ctx context.Context, params acp.%s) error {\n",
				m.GoName, m.ReqType)
			fmt.Fprintf(&buf, "\treturn a.sender.SendNotification(ctx, %s, params)\n", constName)
			buf.WriteString("}\n\n")
		} else {
			fmt.Fprintf(&buf, "func (a *AgentConnection) %s(ctx context.Context, params acp.%s) (acp.%s, error) {\n",
				m.GoName, m.ReqType, m.RespType)
			fmt.Fprintf(&buf, "\treturn jsonrpc.SendRequestTyped[acp.%s](a.sender, ctx, %s, params)\n",
				m.RespType, constName)
			buf.WriteString("}\n\n")
		}
	}

	return formatSource(buf.String())
}

// sessionCreatingMethods lists wire methods whose client outbound
// implementation needs to start a session listener after the RPC call
// succeeds (for Streamable HTTP transports).
var sessionCreatingWireMethods = map[string]bool{
	"session/new":  true,
	"session/load": true,
}

// sessionIDExpr returns the Go expression to extract the session ID for a
// session-creating method. If the response type contains a sessionId property,
// it returns "resp.SessionID"; otherwise it falls back to "params.SessionID".
func (g *Generator) sessionIDExpr(m MethodInfo) string {
	if m.RespType != "" {
		if respSchema, ok := g.schema.Defs[m.RespType]; ok && respSchema != nil {
			if _, hasSessionID := respSchema.Properties["sessionId"]; hasSessionID {
				return "resp.SessionID"
			}
		}
	}
	return "params.SessionID"
}

// renderClientOutbound generates outbound methods on ClientConnection.
// The client sends to the agent, so it uses Agent-side method constants and types.
//
// Session-creating methods (session/new, session/load) get extra logic to
// automatically start a GET SSE listener for the new session on Streamable
// HTTP transports.
func (g *Generator) renderClientOutbound(pkg string, agentMethods []MethodInfo) ([]byte, error) {
	var buf strings.Builder

	buf.WriteString("// Code generated by cmd/generate; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg)
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\n")
	buf.WriteString("\tacp \"github.com/eino-contrib/acp\"\n")
	buf.WriteString("\t\"github.com/eino-contrib/acp/internal/jsonrpc\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("// --- Outbound: Client sends to Agent (generated) ---\n\n")

	for _, m := range agentMethods {
		constName := fmt.Sprintf("acp.MethodAgent%s", m.GoName)
		if m.IsNotify {
			fmt.Fprintf(&buf, "func (c *ClientConnection) %s(ctx context.Context, params acp.%s) error {\n",
				m.GoName, m.ReqType)
			fmt.Fprintf(&buf, "\treturn c.conn.SendNotification(ctx, %s, params)\n", constName)
			buf.WriteString("}\n\n")
		} else if sessionCreatingWireMethods[m.WireMethod] {
			// Session-creating request: after the RPC succeeds, delegate
			// session-listener startup to ClientConnection.startSessionListener.
			// The session ID source depends on the method:
			//   session/new  → resp.SessionID  (allocated by the agent)
			//   session/load → params.SessionID (provided by the client)
			sessionIDExpr := g.sessionIDExpr(m)

			fmt.Fprintf(&buf, "// %s sends a %s request to the agent. When the underlying\n", m.GoName, m.WireMethod)
			fmt.Fprintf(&buf, "// transport supports session listeners (e.g. Streamable HTTP), the\n")
			fmt.Fprintf(&buf, "// ClientConnection automatically opens a GET SSE listener for the new\n")
			fmt.Fprintf(&buf, "// session so that server-initiated messages are received without extra\n")
			fmt.Fprintf(&buf, "// caller effort.\n")
			fmt.Fprintf(&buf, "//\n")
			fmt.Fprintf(&buf, "// The returned error reflects the RPC outcome only. Listener failures\n")
			fmt.Fprintf(&buf, "// are reported via the handler registered with\n")
			fmt.Fprintf(&buf, "// WithSessionListenerErrorHandler (or logged if none is set).\n")
			fmt.Fprintf(&buf, "func (c *ClientConnection) %s(ctx context.Context, params acp.%s) (acp.%s, error) {\n",
				m.GoName, m.ReqType, m.RespType)
			fmt.Fprintf(&buf, "\tresp, err := jsonrpc.SendRequestTyped[acp.%s](c.conn, ctx, %s, params)\n",
				m.RespType, constName)
			buf.WriteString("\tif err != nil {\n")
			buf.WriteString("\t\treturn resp, err\n")
			buf.WriteString("\t}\n")
			fmt.Fprintf(&buf, "\tc.startSessionListener(ctx, string(%s))\n", sessionIDExpr)
			buf.WriteString("\treturn resp, nil\n")
			buf.WriteString("}\n\n")
		} else {
			fmt.Fprintf(&buf, "func (c *ClientConnection) %s(ctx context.Context, params acp.%s) (acp.%s, error) {\n",
				m.GoName, m.ReqType, m.RespType)
			fmt.Fprintf(&buf, "\treturn jsonrpc.SendRequestTyped[acp.%s](c.conn, ctx, %s, params)\n",
				m.RespType, constName)
			buf.WriteString("}\n\n")
		}
	}

	return formatSource(buf.String())
}

// renderHandlers generates the four handler registration functions:
//   - newAgentRequestHandlers
//   - newAgentNotificationHandlers
//   - newClientRequestHandlers
//   - newClientNotificationHandlers
func (g *Generator) renderHandlers(pkg string, agentMethods, clientMethods []MethodInfo) ([]byte, error) {
	var buf strings.Builder

	buf.WriteString("// Code generated by cmd/generate; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg)
	buf.WriteString("import acp \"github.com/eino-contrib/acp\"\n\n")

	// Agent request handlers
	buf.WriteString("func newAgentRequestHandlers(agent acp.Agent, conn *AgentConnection) map[string]requestDispatcher {\n")
	buf.WriteString("\treturn map[string]requestDispatcher{\n")
	for _, m := range agentMethods {
		if !m.IsNotify {
			fmt.Fprintf(&buf, "\t\tacp.MethodAgent%s: bindRequestHandler(agent.%s),\n", m.GoName, m.GoName)
		}
	}
	buf.WriteString("\t}\n}\n\n")

	// Agent notification handlers
	buf.WriteString("func newAgentNotificationHandlers(conn *AgentConnection) map[string]notificationDispatcher {\n")
	buf.WriteString("\treturn map[string]notificationDispatcher{\n")
	for _, m := range agentMethods {
		if m.IsNotify {
			fmt.Fprintf(&buf, "\t\tacp.MethodAgent%s: bindNotificationHandler(%q, conn.agent.%s),\n",
				m.GoName, m.WireMethod+" notification", m.GoName)
		}
	}
	buf.WriteString("\t}\n}\n\n")

	// Client request handlers
	buf.WriteString("func newClientRequestHandlers(client acp.Client) map[string]requestDispatcher {\n")
	buf.WriteString("\treturn map[string]requestDispatcher{\n")
	for _, m := range clientMethods {
		if !m.IsNotify {
			fmt.Fprintf(&buf, "\t\tacp.MethodClient%s: bindRequestHandler(client.%s),\n", m.GoName, m.GoName)
		}
	}
	buf.WriteString("\t}\n}\n\n")

	// Client notification handlers
	buf.WriteString("func newClientNotificationHandlers(client acp.Client) map[string]notificationDispatcher {\n")
	buf.WriteString("\treturn map[string]notificationDispatcher{\n")
	for _, m := range clientMethods {
		if m.IsNotify {
			fmt.Fprintf(&buf, "\t\tacp.MethodClient%s: bindNotificationHandler(%q, client.%s),\n",
				m.GoName, m.WireMethod+" notification", m.GoName)
		}
	}
	buf.WriteString("\t}\n}\n")

	return formatSource(buf.String())
}
