package main

import (
	"fmt"
	"sort"
	"strings"
)

// GenerateMethodMetadata produces methods_gen.go containing generated ACP
// method capability metadata.
func (g *Generator) GenerateMethodMetadata(pkg string) ([]byte, error) {
	methods := append(
		g.buildMethods(g.meta.AgentMethods, "agent"),
		g.buildMethods(g.meta.ClientMethods, "client")...,
	)
	sort.Slice(methods, func(i, j int) bool {
		return methods[i].WireMethod < methods[j].WireMethod
	})

	entries := g.buildMetadataEntries(methods)

	var buf strings.Builder
	buf.WriteString("// Code generated by cmd/generate; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg)
	buf.WriteString("var methodMetadata = map[string]Metadata{\n")
	for _, e := range entries {
		fmt.Fprintf(&buf, "\t%q: {\n", e.WireMethod)
		fmt.Fprintf(&buf, "\t\tKey: %q,\n", e.Key)
		fmt.Fprintf(&buf, "\t\tWireMethod: %q,\n", e.WireMethod)
		fmt.Fprintf(&buf, "\t\tSide: %s,\n", e.Side)
		fmt.Fprintf(&buf, "\t\tNotification: %t,\n", e.Notification)
		fmt.Fprintf(&buf, "\t\tSessionBound: %t,\n", e.SessionBound)
		fmt.Fprintf(&buf, "\t\tSessionHeaderRequired: %t,\n", e.SessionHeaderRequired)
		fmt.Fprintf(&buf, "\t\tSessionCreating: %t,\n", e.SessionCreating)
		fmt.Fprintf(&buf, "\t},\n")
	}
	buf.WriteString("}\n")

	return formatSource(buf.String())
}

// metadataEntry holds the resolved metadata for a single wire method. Methods
// listed on both the agent and client sides (e.g. mcp/message) are collapsed
// into a single entry with Side set to SideBoth, since methodMetadata is keyed
// by wire method.
type metadataEntry struct {
	Key                   string
	WireMethod            string
	Side                  string
	Notification          bool
	SessionBound          bool
	SessionHeaderRequired bool
	SessionCreating       bool
}

func (g *Generator) buildMetadataEntries(methods []MethodInfo) []metadataEntry {
	byWire := make(map[string]*metadataEntry)
	var order []string

	for _, method := range methods {
		side := "SideAgent"
		if method.Side == "client" {
			side = "SideClient"
		}
		sessionCreating := method.Side == "agent" &&
			(method.WireMethod == "session/new" || method.WireMethod == "session/load")
		sessionBound := sessionCreating || g.methodHasRequiredProperty(method, "sessionId")
		sessionHeaderRequired := method.Side == "agent" && sessionBound && !sessionCreating

		if existing, ok := byWire[method.WireMethod]; ok {
			if existing.Side != side {
				existing.Side = "SideBoth"
			}
			existing.SessionBound = existing.SessionBound || sessionBound
			existing.SessionHeaderRequired = existing.SessionHeaderRequired || sessionHeaderRequired
			existing.SessionCreating = existing.SessionCreating || sessionCreating
			continue
		}

		byWire[method.WireMethod] = &metadataEntry{
			Key:                   method.Key,
			WireMethod:            method.WireMethod,
			Side:                  side,
			Notification:          method.IsNotify,
			SessionBound:          sessionBound,
			SessionHeaderRequired: sessionHeaderRequired,
			SessionCreating:       sessionCreating,
		}
		order = append(order, method.WireMethod)
	}

	entries := make([]metadataEntry, 0, len(order))
	for _, wire := range order {
		entries = append(entries, *byWire[wire])
	}
	return entries
}

func (g *Generator) methodHasRequiredProperty(method MethodInfo, property string) bool {
	if method.ReqType == "" {
		return false
	}
	schema, ok := g.schema.Defs[method.ReqType]
	if !ok || schema == nil {
		return false
	}
	for _, required := range schema.Required {
		if required == property {
			return true
		}
	}
	return false
}
