package main

import (
	"fmt"
	"strings"
)

// GenerateBaseFile produces base.go with strict default implementations for
// both the Agent and Client interfaces.
func (g *Generator) GenerateBaseFile(pkg string) ([]byte, error) {
	agentMethods := g.buildMethods(g.meta.AgentMethods, "agent")
	clientMethods := g.buildMethods(g.meta.ClientMethods, "client")

	var buf strings.Builder
	buf.WriteString("// Code generated by cmd/generate; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg)
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString("func methodNotSupported(method string) *RPCError {\n")
	buf.WriteString("\treturn ErrMethodNotFound(method)\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func notificationNotImplemented(method string) error {\n")
	buf.WriteString("\treturn fmt.Errorf(\"notification handler not implemented: %s\", method)\n")
	buf.WriteString("}\n\n")

	buf.WriteString("// BaseAgent provides strict default implementations for the Agent interface.\n")
	buf.WriteString("//\n")
	buf.WriteString("// All request-style methods return method-not-found by default so missing\n")
	buf.WriteString("// capabilities fail loudly instead of silently succeeding with empty results.\n")
	buf.WriteString("// Notification-style methods return explicit errors so missing protocol hooks do\n")
	buf.WriteString("// not silently disappear during integration.\n")
	buf.WriteString("type BaseAgent struct{}\n\n")
	for _, m := range agentMethods {
		if m.IsNotify {
			fmt.Fprintf(&buf, "func (BaseAgent) %s(context.Context, %s) error {\n", m.GoName, m.ReqType)
			fmt.Fprintf(&buf, "\treturn notificationNotImplemented(MethodAgent%s)\n", m.GoName)
			buf.WriteString("}\n\n")
			continue
		}
		fmt.Fprintf(&buf, "func (BaseAgent) %s(context.Context, %s) (%s, error) {\n", m.GoName, m.ReqType, m.RespType)
		fmt.Fprintf(&buf, "\treturn %s{}, methodNotSupported(MethodAgent%s)\n", m.RespType, m.GoName)
		buf.WriteString("}\n\n")
	}
	buf.WriteString("var _ Agent = BaseAgent{}\n\n")

	buf.WriteString("// BaseClient provides strict default implementations for the Client interface.\n")
	buf.WriteString("//\n")
	buf.WriteString("// Request-style methods return method-not-found by default so client capability\n")
	buf.WriteString("// mismatches are explicit. SessionUpdate also reports an explicit error so UI\n")
	buf.WriteString("// state notifications do not silently disappear when the embedding client has\n")
	buf.WriteString("// not wired the callback yet.\n")
	buf.WriteString("type BaseClient struct{}\n\n")
	for _, m := range clientMethods {
		if m.IsNotify {
			fmt.Fprintf(&buf, "func (BaseClient) %s(context.Context, %s) error {\n", m.GoName, m.ReqType)
			fmt.Fprintf(&buf, "\treturn notificationNotImplemented(MethodClient%s)\n", m.GoName)
			buf.WriteString("}\n\n")
			continue
		}
		fmt.Fprintf(&buf, "func (BaseClient) %s(context.Context, %s) (%s, error) {\n", m.GoName, m.ReqType, m.RespType)
		fmt.Fprintf(&buf, "\treturn %s{}, methodNotSupported(MethodClient%s)\n", m.RespType, m.GoName)
		buf.WriteString("}\n\n")
	}
	buf.WriteString("var _ Client = BaseClient{}\n")

	return formatSource(buf.String())
}
