package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// Generator holds state for code generation.
type Generator struct {
	schema *Schema
	meta   *Meta
	buf    strings.Builder

	needJSON bool // whether "encoding/json" is needed
	needFmt  bool // whether "fmt" is needed
}

// NewGenerator creates a new Generator.
func NewGenerator(schema *Schema, meta *Meta) *Generator {
	return &Generator{
		schema: schema,
		meta:   meta,
	}
}

// Generate produces the full generated Go source code.
func (g *Generator) Generate(pkg string) ([]byte, error) {
	defs := GetDefinitions(g.schema)

	// Pre-scan to determine imports
	for _, d := range defs {
		switch d.Type {
		case TypeDiscriminatedUnion:
			g.needJSON = true
			g.needFmt = true
		case TypeStruct:
			if g.structNeedsJSON(d.Schema) {
				g.needJSON = true
			}
		}
	}

	// Write header
	g.buf.WriteString("// Code generated by cmd/generate; DO NOT EDIT.\n\n")
	fmt.Fprintf(&g.buf, "package %s\n\n", pkg)

	// Write imports
	g.writeImports()

	// Generate enums first
	for _, d := range defs {
		if d.Type == TypeEnum {
			g.generateEnum(d)
		}
	}

	// Generate discriminated union variant types and wrappers
	for _, d := range defs {
		if d.Type == TypeDiscriminatedUnion {
			g.generateDiscriminatedUnion(d)
		}
	}

	// Generate structs
	for _, d := range defs {
		if d.Type == TypeStruct {
			g.generateStruct(d)
		}
	}

	// Generate primitives and type aliases
	for _, d := range defs {
		switch d.Type {
		case TypePrimitive:
			g.generatePrimitive(d)
		case TypeArray:
			g.generateArray(d)
		case TypeRef:
			g.generateTypeAlias(d)
		case TypeSimpleUnion:
			g.generateSimpleUnion(d)
		}
	}

	// Generate extension payload types (schema-less definitions) as json.RawMessage aliases.
	for _, d := range defs {
		if isExtPayloadType(d.Name) {
			g.needJSON = true
			goName := toTitleCase(d.Name)
			g.writeComment(goName, d.Schema.Description)
			fmt.Fprintf(&g.buf, "type %s = json.RawMessage\n\n", goName)
		}
	}

	// Generate Validate() methods for struct types with required fields
	g.generateValidateMethods(defs)

	// Generate UnmarshalJSON with default values for struct types
	g.generateDefaultUnmarshalers(defs)

	// Generate method constants from meta
	if g.meta != nil {
		g.generateConstants()
	}

	// Format the output
	return formatSource(g.buf.String())
}

func formatSource(src string) ([]byte, error) {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return []byte(src), fmt.Errorf("format error: %w\n--- raw source available in output ---", err)
	}
	return formatted, nil
}

func (g *Generator) writeImports() {
	if !g.needJSON && !g.needFmt {
		return
	}
	g.buf.WriteString("import (\n")
	if g.needJSON {
		g.buf.WriteString("\t\"encoding/json\"\n")
	}
	if g.needFmt {
		g.buf.WriteString("\t\"fmt\"\n")
	}
	g.buf.WriteString(")\n\n")
}

func (g *Generator) structNeedsJSON(s *Schema) bool {
	if s.Properties == nil {
		return false
	}
	for _, prop := range s.Properties {
		goType := resolveGoType(prop, true)
		if goType == "json.RawMessage" {
			return true
		}
		// Check for map[string]any which comes from _meta
		if goType == "map[string]any" {
			return false // no json import needed for map[string]any
		}
	}
	return false
}

// writeComment writes a Go doc comment from a schema description.
func (g *Generator) writeComment(name string, desc *string) {
	if desc == nil || *desc == "" {
		return
	}
	lines := strings.Split(strings.TrimSpace(*desc), "\n")
	for _, line := range lines {
		fmt.Fprintf(&g.buf, "// %s\n", strings.TrimSpace(line))
	}
}

// writeIndentedComment writes a comment inside a const/var block (tab-indented).
func (g *Generator) writeIndentedComment(comment string) {
	lines := strings.Split(strings.TrimSpace(comment), "\n")
	for _, line := range lines {
		fmt.Fprintf(&g.buf, "\t// %s\n", strings.TrimSpace(line))
	}
}

// === Enum Generation ===

func (g *Generator) generateEnum(d Definition) {
	s := d.Schema
	goName := toTitleCase(d.Name)

	g.writeComment(goName, s.Description)

	// Determine enum values and base type
	var values []enumValue
	var baseType string

	if len(s.Enum) > 0 {
		// Direct enum field
		values, baseType = g.extractDirectEnum(s)
	} else if len(s.OneOf) > 0 {
		values, baseType = g.extractConstEnum(s.OneOf, s)
	} else if len(s.AnyOf) > 0 {
		values, baseType = g.extractConstEnum(filterNull(s.AnyOf), s)
	}

	if len(values) == 0 {
		return
	}

	fmt.Fprintf(&g.buf, "type %s %s\n\n", goName, baseType)
	g.buf.WriteString("const (\n")
	for _, v := range values {
		if v.comment != "" {
			g.writeIndentedComment(v.comment)
		}
		if baseType == "string" {
			fmt.Fprintf(&g.buf, "\t%s%s %s = %q\n", goName, toTitleCase(v.name), goName, v.raw)
		} else {
			fmt.Fprintf(&g.buf, "\t%s%s %s = %s\n", goName, toTitleCase(v.name), goName, v.raw)
		}
	}
	g.buf.WriteString(")\n\n")
}

type enumValue struct {
	name    string
	raw     string
	comment string
}

func (g *Generator) extractDirectEnum(s *Schema) ([]enumValue, string) {
	var values []enumValue
	baseType := "string"

	for _, raw := range s.Enum {
		var str string
		if err := json.Unmarshal(raw, &str); err == nil {
			name := str
			if name == "" {
				name = "Empty"
			}
			values = append(values, enumValue{name: name, raw: str})
			continue
		}
		var num int64
		if err := json.Unmarshal(raw, &num); err == nil {
			baseType = "int"
			values = append(values, enumValue{name: fmt.Sprintf("Code%d", num), raw: fmt.Sprintf("%d", num)})
		}
	}
	return values, baseType
}

func (g *Generator) extractConstEnum(variants []*Schema, parent *Schema) ([]enumValue, string) {
	var values []enumValue
	baseType := "string"

	for _, v := range variants {
		if v.Const == nil {
			continue
		}
		if str, ok := v.Const.StringValue(); ok {
			name := str
			if name == "" {
				name = "Empty"
			}
			comment := ""
			if v.Description != nil {
				comment = strings.TrimSpace(*v.Description)
			}
			values = append(values, enumValue{name: name, raw: str, comment: comment})
		} else if num, ok := v.Const.IntValue(); ok {
			baseType = "int"
			comment := ""
			if v.Description != nil {
				comment = strings.TrimSpace(*v.Description)
			}
			name := ""
			if v.Title != "" {
				name = toTitleCase(v.Title) // Convert "Parse error" -> "ParseError"
			} else {
				if num < 0 {
					name = fmt.Sprintf("Neg%d", -num)
				} else {
					name = fmt.Sprintf("Code%d", num)
				}
			}
			values = append(values, enumValue{name: name, raw: fmt.Sprintf("%d", num), comment: comment})
		}
	}
	return values, baseType
}

// === Struct Generation ===

func (g *Generator) generateStruct(d Definition) {
	s := d.Schema
	goName := toTitleCase(d.Name)

	// Skip dispatch/wrapper types that aren't useful as Go structs
	if isDispatchType(d.Name) {
		return
	}

	// Handle allOf: merge properties from all schemas
	if len(s.AllOf) > 0 {
		s = mergeAllOf(s)
	}

	if s.Properties == nil && !hasObjectType(s) {
		return
	}

	g.writeComment(goName, s.Description)
	fmt.Fprintf(&g.buf, "type %s struct {\n", goName)

	// Build sorted field list
	fields := g.buildStructFields(s)
	for _, f := range fields {
		if f.comment != "" {
			fmt.Fprintf(&g.buf, "\t// %s\n", f.comment)
		}
		fmt.Fprintf(&g.buf, "\t%s %s `json:\"%s\"`\n", f.goName, f.goType, f.jsonTag)
	}

	g.buf.WriteString("}\n\n")

	// Generate GetSessionID() for types that have a SessionID field,
	// satisfying the session.SessionIDProvider interface for fast-path
	// session ID extraction without reflection.
	for _, f := range fields {
		if f.goName == "SessionID" {
			fmt.Fprintf(&g.buf, "func (x %s) GetSessionID() string { return string(x.SessionID) }\n\n", goName)
			break
		}
	}

	// Generate GetProtocolVersion() for types that have a ProtocolVersion
	// field, enabling fast-path protocol version extraction without
	// marshal/unmarshal round-trips.
	for _, f := range fields {
		if f.goName == "ProtocolVersion" {
			fmt.Fprintf(&g.buf, "func (x %s) GetProtocolVersion() ProtocolVersion { return x.ProtocolVersion }\n\n", goName)
			break
		}
	}
}

type structField struct {
	goName  string
	goType  string
	jsonTag string
	comment string
}

func (g *Generator) buildStructFields(s *Schema) []structField {
	if s.Properties == nil {
		return nil
	}

	requiredSet := make(map[string]bool)
	for _, r := range s.Required {
		requiredSet[r] = true
	}

	var fields []structField

	// Sort property names for deterministic output
	propNames := sortedKeys(s.Properties)

	for _, propName := range propNames {
		prop := s.Properties[propName]
		isRequired := requiredSet[propName]

		goName := toTitleCase(propName)
		goType := g.resolveFieldType(prop, isRequired)

		jsonTag := propName
		if !isRequired {
			jsonTag += ",omitempty"
		}

		// Special case: _meta
		if propName == "_meta" {
			goName = "Meta"
			goType = "map[string]any"
			jsonTag = "_meta,omitempty"
		}

		fields = append(fields, structField{
			goName:  goName,
			goType:  goType,
			jsonTag: jsonTag,
		})
	}

	return fields
}

func (g *Generator) resolveFieldType(s *Schema, required bool) string {
	if s == nil {
		return "any"
	}

	if len(s.OneOf) > 0 {
		nonNull := filterNull(s.OneOf)
		if len(nonNull) == 1 {
			return g.resolveFieldType(nonNull[0], required)
		}
		g.needJSON = true
		return "json.RawMessage"
	}

	// $ref
	if s.Ref != "" {
		typeName := toTitleCase(resolveRef(s.Ref))
		if !required {
			return "*" + typeName
		}
		return typeName
	}

	// allOf with single ref
	if len(s.AllOf) == 1 && s.AllOf[0].Ref != "" {
		typeName := toTitleCase(resolveRef(s.AllOf[0].Ref))
		if !required {
			return "*" + typeName
		}
		return typeName
	}

	// anyOf: filter nulls, use first non-null
	if len(s.AnyOf) > 0 {
		nonNull := filterNull(s.AnyOf)
		if len(nonNull) == 1 {
			return g.resolveFieldType(nonNull[0], required)
		}
		g.needJSON = true
		return "json.RawMessage"
	}

	// Nullable types: ["string", "null"], ["array", "null"], etc.
	if len(s.Type) == 2 && s.Type.IsNullable() {
		nonNull := s.Type.NonNull()
		if nonNull == "array" {
			if s.Items != nil {
				itemType := g.resolveFieldType(s.Items, true)
				return "[]" + itemType
			}
			return "[]any"
		}
		baseType := mapJSONTypeToGo(nonNull)
		if baseType == "string" {
			return "string"
		}
		return "*" + baseType
	}

	if len(s.Type) == 0 {
		g.needJSON = true
		return "json.RawMessage"
	}

	baseType := s.Type[0]
	switch baseType {
	case "object":
		if s.AdditionalProperties != nil {
			if s.AdditionalProperties.Schema != nil {
				valType := g.resolveFieldType(s.AdditionalProperties.Schema, true)
				return "map[string]" + valType
			}
			return "map[string]any"
		}
		if len(s.Properties) == 0 {
			return "map[string]any"
		}
		g.needJSON = true
		return "json.RawMessage"
	case "array":
		if s.Items != nil {
			itemType := g.resolveFieldType(s.Items, true)
			return "[]" + itemType
		}
		return "[]any"
	default:
		goType := mapJSONTypeToGo(baseType)
		if !required && goType != "string" && goType != "bool" {
			return "*" + goType
		}
		return goType
	}
}

// === Primitive / TypeAlias / SimpleUnion Generation ===

func (g *Generator) generateArray(d Definition) {
	goName := toTitleCase(d.Name)
	s := d.Schema

	g.writeComment(goName, s.Description)

	goType := "[]any"
	if s.Items != nil {
		goType = "[]" + g.resolveFieldType(s.Items, true)
	}

	fmt.Fprintf(&g.buf, "type %s %s\n\n", goName, goType)
}

func (g *Generator) generatePrimitive(d Definition) {
	goName := toTitleCase(d.Name)
	s := d.Schema

	g.writeComment(goName, s.Description)

	if len(s.Type) > 0 {
		goType := mapJSONTypeToGo(s.Type.NonNull())
		if goType == "" {
			goType = mapJSONTypeToGo(s.Type[0])
		}
		fmt.Fprintf(&g.buf, "type %s %s\n\n", goName, goType)
		return
	}

	if g.generateSpecialUnion(goName, s) {
		return
	}

	// anyOf with mixed primitives
	fmt.Fprintf(&g.buf, "type %s any\n\n", goName)
}

func (g *Generator) generateSpecialUnion(goName string, s *Schema) bool {
	variants := s.AnyOf
	if len(variants) == 0 {
		variants = s.OneOf
	}
	if len(variants) == 0 {
		return false
	}

	if isPrimitiveUnion(variants) {
		g.generatePrimitiveValueUnion(goName, variants)
		return true
	}

	objectVariants := normalizeObjectVariants(variants)
	if len(objectVariants) == len(variants) && len(objectVariants) >= 2 {
		g.generateInlineObjectUnion(goName, objectVariants)
		return true
	}

	return false
}

func isPrimitiveUnion(variants []*Schema) bool {
	if len(variants) == 0 {
		return false
	}
	for _, v := range variants {
		if v == nil || len(v.Type) != 1 {
			return false
		}
		switch v.Type[0] {
		case "null", "string", "integer", "number", "boolean":
		default:
			return false
		}
	}
	return true
}

func normalizeObjectVariants(variants []*Schema) []*Schema {
	result := make([]*Schema, 0, len(variants))
	for _, v := range variants {
		if v == nil {
			return nil
		}
		normalized := v
		if len(normalized.AllOf) > 0 {
			normalized = mergeAllOf(normalized)
		}
		if len(normalized.Type) == 0 && len(normalized.Properties) > 0 {
			result = append(result, normalized)
			continue
		}
		if hasObjectType(normalized) || len(normalized.Properties) > 0 {
			result = append(result, normalized)
			continue
		}
		return nil
	}
	return result
}

func primitiveVariantSuffix(s *Schema) string {
	if s == nil || len(s.Type) == 0 {
		return "Value"
	}
	switch s.Type[0] {
	case "null":
		return "Null"
	case "string":
		return "String"
	case "integer":
		return "Int64"
	case "number":
		return "Float64"
	case "boolean":
		return "Bool"
	default:
		if s.Title != "" {
			return toTitleCase(s.Title)
		}
		return "Value"
	}
}

func primitiveVariantGoType(s *Schema) string {
	if s == nil || len(s.Type) == 0 {
		return "any"
	}
	return mapJSONTypeToGo(s.Type[0])
}

func (g *Generator) generatePrimitiveValueUnion(goName string, variants []*Schema) {
	g.needJSON = true
	g.needFmt = true

	fmt.Fprintf(&g.buf, "type %s struct {\n", goName)
	fmt.Fprintf(&g.buf, "\traw json.RawMessage\n")
	fmt.Fprintf(&g.buf, "}\n\n")

	for _, variant := range variants {
		if len(variant.Type) == 0 {
			continue
		}
		suffix := primitiveVariantSuffix(variant)
		if variant.Type[0] == "null" {
			fmt.Fprintf(&g.buf, "func New%s%s() %s {\n", goName, suffix, goName)
			fmt.Fprintf(&g.buf, "\treturn %s{raw: json.RawMessage(`null`)}\n", goName)
			fmt.Fprintf(&g.buf, "}\n\n")
			continue
		}
		goType := primitiveVariantGoType(variant)
		fmt.Fprintf(&g.buf, "func New%s%s(v %s) %s {\n", goName, suffix, goType, goName)
		fmt.Fprintf(&g.buf, "\tdata, err := json.Marshal(v)\n")
		fmt.Fprintf(&g.buf, "\tif err != nil {\n")
		fmt.Fprintf(&g.buf, "\t\t// Marshal should never fail for primitive types; panic only if it does\n")
		fmt.Fprintf(&g.buf, "\t\tpanic(err)\n")
		fmt.Fprintf(&g.buf, "\t}\n")
		fmt.Fprintf(&g.buf, "\treturn %s{raw: data}\n", goName)
		fmt.Fprintf(&g.buf, "}\n\n")
	}

	fmt.Fprintf(&g.buf, "func (v %s) MarshalJSON() ([]byte, error) {\n", goName)
	fmt.Fprintf(&g.buf, "\tif len(v.raw) == 0 {\n")
	fmt.Fprintf(&g.buf, "\t\treturn []byte(`null`), nil\n")
	fmt.Fprintf(&g.buf, "\t}\n")
	fmt.Fprintf(&g.buf, "\treturn v.raw, nil\n")
	fmt.Fprintf(&g.buf, "}\n\n")

	fmt.Fprintf(&g.buf, "func (v *%s) UnmarshalJSON(data []byte) error {\n", goName)
	for _, variant := range variants {
		if len(variant.Type) == 0 {
			continue
		}
		switch variant.Type[0] {
		case "null":
			fmt.Fprintf(&g.buf, "\t{\n")
			fmt.Fprintf(&g.buf, "\t\tvar candidate any\n")
			fmt.Fprintf(&g.buf, "\t\tif err := json.Unmarshal(data, &candidate); err == nil && candidate == nil {\n")
			fmt.Fprintf(&g.buf, "\t\t\tv.raw = append(v.raw[:0], data...)\n")
			fmt.Fprintf(&g.buf, "\t\t\treturn nil\n")
			fmt.Fprintf(&g.buf, "\t\t}\n")
			fmt.Fprintf(&g.buf, "\t}\n")
		default:
			goType := primitiveVariantGoType(variant)
			fmt.Fprintf(&g.buf, "\t{\n")
			fmt.Fprintf(&g.buf, "\t\tvar candidate %s\n", goType)
			fmt.Fprintf(&g.buf, "\t\tif err := json.Unmarshal(data, &candidate); err == nil {\n")
			fmt.Fprintf(&g.buf, "\t\t\tv.raw = append(v.raw[:0], data...)\n")
			fmt.Fprintf(&g.buf, "\t\t\treturn nil\n")
			fmt.Fprintf(&g.buf, "\t\t}\n")
			fmt.Fprintf(&g.buf, "\t}\n")
		}
	}
	fmt.Fprintf(&g.buf, "\treturn fmt.Errorf(\"data does not match any primitive variant of %s\")\n", goName)
	fmt.Fprintf(&g.buf, "}\n\n")

	fmt.Fprintf(&g.buf, "func (v %s) Raw() json.RawMessage {\n", goName)
	fmt.Fprintf(&g.buf, "\tif len(v.raw) == 0 {\n")
	fmt.Fprintf(&g.buf, "\t\treturn json.RawMessage(`null`)\n")
	fmt.Fprintf(&g.buf, "\t}\n")
	fmt.Fprintf(&g.buf, "\treturn append(json.RawMessage(nil), v.raw...)\n")
	fmt.Fprintf(&g.buf, "}\n\n")

	for _, variant := range variants {
		if len(variant.Type) == 0 {
			continue
		}
		suffix := primitiveVariantSuffix(variant)
		switch variant.Type[0] {
		case "null":
			fmt.Fprintf(&g.buf, "func (v %s) Is%s() bool {\n", goName, suffix)
			fmt.Fprintf(&g.buf, "\tvar candidate any\n")
			fmt.Fprintf(&g.buf, "\treturn len(v.raw) > 0 && json.Unmarshal(v.raw, &candidate) == nil && candidate == nil\n")
			fmt.Fprintf(&g.buf, "}\n\n")
		default:
			goType := primitiveVariantGoType(variant)
			fmt.Fprintf(&g.buf, "func (v %s) As%s() (%s, bool) {\n", goName, suffix, goType)
			fmt.Fprintf(&g.buf, "\tvar candidate %s\n", goType)
			fmt.Fprintf(&g.buf, "\tif len(v.raw) == 0 || json.Unmarshal(v.raw, &candidate) != nil {\n")
			fmt.Fprintf(&g.buf, "\t\tvar zero %s\n", goType)
			fmt.Fprintf(&g.buf, "\t\treturn zero, false\n")
			fmt.Fprintf(&g.buf, "\t}\n")
			fmt.Fprintf(&g.buf, "\treturn candidate, true\n")
			fmt.Fprintf(&g.buf, "}\n\n")
		}
	}
}

func (g *Generator) generateInlineObjectUnion(goName string, variants []*Schema) {
	var refTypes []string
	var unionVariants []variantRef
	for i, variant := range variants {
		wrapperName := goName + fmt.Sprintf("Variant%d", i+1)
		if variant.Title != "" {
			wrapperName = goName + toTitleCase(variant.Title)
		}
		fmt.Fprintf(&g.buf, "type %s struct {\n", wrapperName)
		fields := g.buildStructFields(variant)
		for _, f := range fields {
			if f.comment != "" {
				fmt.Fprintf(&g.buf, "\t// %s\n", f.comment)
			}
			fmt.Fprintf(&g.buf, "\t%s %s `json:\"%s\"`\n", f.goName, f.goType, f.jsonTag)
		}
		fmt.Fprintf(&g.buf, "}\n\n")
		refTypes = append(refTypes, wrapperName)
		unionVariants = append(unionVariants, variantRef{goType: wrapperName, schema: variant})
	}
	g.generateTryParseUnion(goName, refTypes, findDistinguishingFields(unionVariants), variantArrayIndices(unionVariants))
}

func (g *Generator) generateTypeAlias(d Definition) {
	goName := toTitleCase(d.Name)
	s := d.Schema

	var targetRef string
	if s.Ref != "" {
		targetRef = s.Ref
	} else if len(s.AllOf) == 1 && s.AllOf[0].Ref != "" {
		targetRef = s.AllOf[0].Ref
	}

	// Handle anyOf/oneOf with single non-null variant that is a ref
	if targetRef == "" {
		variants := s.AnyOf
		if len(variants) == 0 {
			variants = s.OneOf
		}
		nonNull := filterNull(variants)
		if len(nonNull) == 1 {
			v := nonNull[0]
			if v.Ref != "" {
				targetRef = v.Ref
			} else if len(v.AllOf) == 1 && v.AllOf[0].Ref != "" {
				targetRef = v.AllOf[0].Ref
			}
		}
	}

	if targetRef != "" {
		targetName := toTitleCase(resolveRef(targetRef))
		g.writeComment(goName, s.Description)
		fmt.Fprintf(&g.buf, "type %s = %s\n\n", goName, targetName)
		return
	}
}

func (g *Generator) generateSimpleUnion(d Definition) {
	goName := toTitleCase(d.Name)
	s := d.Schema

	g.writeComment(goName, s.Description)

	variants := s.OneOf
	if len(variants) == 0 {
		variants = s.AnyOf
	}
	nonNull := filterNull(variants)

	// If single ref remaining
	if len(nonNull) == 1 {
		ref := resolveVariantRef(nonNull[0])
		if ref != "" {
			targetName := toTitleCase(resolveRef(ref))
			fmt.Fprintf(&g.buf, "type %s = %s\n\n", goName, targetName)
			return
		}
	}

	// Collect resolved ref types for try-parse union
	var varRefs []variantRef
	for _, v := range nonNull {
		ref := resolveVariantRef(v)
		if ref != "" {
			refName := resolveRef(ref)
			// Look up the referenced schema to get required fields info
			var refSchema *Schema
			if g.schema != nil && g.schema.Defs != nil {
				refSchema = g.schema.Defs[refName]
			}
			varRefs = append(varRefs, variantRef{goType: toTitleCase(refName), schema: refSchema})
			continue
		}
		// Handle array-of-ref: generate as []RefType
		if v.Type.Contains("array") && v.Items != nil && v.Items.Ref != "" {
			itemType := toTitleCase(resolveRef(v.Items.Ref))
			itemRefName := resolveRef(v.Items.Ref)
			var itemSchema *Schema
			if g.schema != nil && g.schema.Defs != nil {
				itemSchema = g.schema.Defs[itemRefName]
			}
			varRefs = append(varRefs, variantRef{goType: "[]" + itemType, schema: itemSchema, isArray: true})
			continue
		}
	}

	// If all variants are resolvable, generate a try-parse union
	if len(varRefs) == len(nonNull) && len(varRefs) >= 2 {
		refTypes := make([]string, len(varRefs))
		for i, vr := range varRefs {
			refTypes[i] = vr.goType
		}
		// Find distinguishing required fields
		distinguishingFields := findDistinguishingFields(varRefs)
		g.generateTryParseUnion(goName, refTypes, distinguishingFields, variantArrayIndices(varRefs))
		return
	}

	fmt.Fprintf(&g.buf, "type %s any\n\n", goName)
}

// findDistinguishingFields finds required fields unique to each variant.
// Returns a map from variant index to a field name that uniquely identifies it.
func findDistinguishingFields(variants []variantRef) map[int]string {
	result := make(map[int]string)

	// Collect required fields for each variant
	type fieldSet map[string]bool
	allFields := make([]fieldSet, len(variants))
	for i, vr := range variants {
		allFields[i] = make(fieldSet)
		if vr.schema != nil && vr.schema.Required != nil {
			for _, f := range vr.schema.Required {
				allFields[i][f] = true
			}
		}
	}

	// For each variant, find a required field not present in other variants' required fields.
	// Sort fields for deterministic output regardless of map iteration order.
	for i, fields := range allFields {
		sorted := make([]string, 0, len(fields))
		for f := range fields {
			sorted = append(sorted, f)
		}
		sort.Strings(sorted)
		for _, f := range sorted {
			unique := true
			for j, otherFields := range allFields {
				if i == j {
					continue
				}
				if otherFields[f] {
					unique = false
					break
				}
			}
			if unique {
				result[i] = f
				break
			}
		}
	}

	return result
}

// generateTryParseUnion generates a union type that tries each variant during unmarshal.
func variantArrayIndices(variants []variantRef) map[int]bool {
	result := make(map[int]bool)
	for i, vr := range variants {
		if vr.isArray {
			result[i] = true
		}
	}
	return result
}

func (g *Generator) generateTryParseUnion(goName string, refTypes []string, distinguishingFields map[int]string, arrayVariantIndices map[int]bool) {
	g.needJSON = true
	g.needFmt = true

	// For slice types, we need wrapper named types since []T can't have methods.
	type variantType struct {
		rawType       string // e.g., "TextResourceContents" or "[]SessionConfigSelectOption"
		wrapperName   string // e.g., "TextResourceContents" or "SessionConfigSelectOptions_SessionConfigSelectOption"
		constructorID string // e.g., "TextResourceContents" or "SessionConfigSelectOptionList"
		isSlice       bool
	}
	var variants []variantType
	for _, rt := range refTypes {
		if strings.HasPrefix(rt, "[]") {
			itemType := strings.TrimPrefix(rt, "[]")
			wrapperName := goName + itemType + "List"
			variants = append(variants, variantType{
				rawType:       rt,
				wrapperName:   wrapperName,
				constructorID: itemType + "List",
				isSlice:       true,
			})
		} else {
			variants = append(variants, variantType{
				rawType:       rt,
				wrapperName:   rt,
				constructorID: rt,
				isSlice:       false,
			})
		}
	}

	// Generate wrapper types for slices
	for _, vt := range variants {
		if vt.isSlice {
			fmt.Fprintf(&g.buf, "type %s %s\n\n", vt.wrapperName, vt.rawType)
		}
	}

	// Marker interface
	markerMethod := fmt.Sprintf("is%sVariant", goName)
	interfaceName := uncapitalize(goName) + "Variant"

	// Implement marker on each type
	for _, vt := range variants {
		fmt.Fprintf(&g.buf, "func (%s) %s() {}\n", vt.wrapperName, markerMethod)
	}
	g.buf.WriteString("\n")

	fmt.Fprintf(&g.buf, "type %s interface{ %s() }\n\n", interfaceName, markerMethod)

	fmt.Fprintf(&g.buf, "type %s struct {\n", goName)
	fmt.Fprintf(&g.buf, "\tvariant %s\n", interfaceName)
	fmt.Fprintf(&g.buf, "}\n\n")

	recv := receiverName(goName)

	// MarshalJSON
	fmt.Fprintf(&g.buf, "func (%s %s) MarshalJSON() ([]byte, error) {\n", recv, goName)
	fmt.Fprintf(&g.buf, "\tif %s.variant == nil {\n", recv)
	fmt.Fprintf(&g.buf, "\t\treturn nil, fmt.Errorf(\"no variant is set for %s\")\n", goName)
	fmt.Fprintf(&g.buf, "\t}\n")
	fmt.Fprintf(&g.buf, "\treturn json.Marshal(%s.variant)\n", recv)
	fmt.Fprintf(&g.buf, "}\n")

	// UnmarshalJSON — use distinguishing fields when available, else try-parse
	fmt.Fprintf(&g.buf, "func (%s *%s) UnmarshalJSON(data []byte) error {\n", recv, goName)

	hasDistinguishing := len(distinguishingFields) > 0
	if hasDistinguishing {
		hasObjectDistinguishing := false
		hasArrayDistinguishing := false
		for i := range distinguishingFields {
			if arrayVariantIndices[i] {
				hasArrayDistinguishing = true
				continue
			}
			hasObjectDistinguishing = true
		}

		// Check keys in raw JSON to distinguish variants.
		// Arrays need special handling because the distinguishing field lives on each item.
		if hasObjectDistinguishing {
			fmt.Fprintf(&g.buf, "\tvar keys map[string]json.RawMessage\n")
			fmt.Fprintf(&g.buf, "\tif err := json.Unmarshal(data, &keys); err == nil {\n")
			for i, vt := range variants {
				if field, ok := distinguishingFields[i]; ok {
					if arrayVariantIndices[i] {
						continue
					}
					varName := fmt.Sprintf("v%d", i)
					fmt.Fprintf(&g.buf, "\t\tif _, ok := keys[%q]; ok {\n", field)
					fmt.Fprintf(&g.buf, "\t\t\tvar %s %s\n", varName, vt.wrapperName)
					fmt.Fprintf(&g.buf, "\t\t\tif err := json.Unmarshal(data, &%s); err != nil {\n", varName)
					fmt.Fprintf(&g.buf, "\t\t\t\treturn err\n")
					fmt.Fprintf(&g.buf, "\t\t\t}\n")
					fmt.Fprintf(&g.buf, "\t\t\t%s.variant = %s\n", recv, varName)
					fmt.Fprintf(&g.buf, "\t\t\treturn nil\n")
					fmt.Fprintf(&g.buf, "\t\t}\n")
				}
			}
			fmt.Fprintf(&g.buf, "\t}\n")
		}
		if hasArrayDistinguishing {
			fmt.Fprintf(&g.buf, "\tvar items []map[string]json.RawMessage\n")
			fmt.Fprintf(&g.buf, "\tif err := json.Unmarshal(data, &items); err == nil && len(items) > 0 {\n")
			for i, vt := range variants {
				field, ok := distinguishingFields[i]
				if !ok || !arrayVariantIndices[i] {
					continue
				}
				varName := fmt.Sprintf("va%d", i)
				fmt.Fprintf(&g.buf, "\t\tif _, ok := items[0][%q]; ok {\n", field)
				fmt.Fprintf(&g.buf, "\t\t\tvar %s %s\n", varName, vt.wrapperName)
				fmt.Fprintf(&g.buf, "\t\t\tif err := json.Unmarshal(data, &%s); err != nil {\n", varName)
				fmt.Fprintf(&g.buf, "\t\t\t\treturn err\n")
				fmt.Fprintf(&g.buf, "\t\t\t}\n")
				fmt.Fprintf(&g.buf, "\t\t\t%s.variant = %s\n", recv, varName)
				fmt.Fprintf(&g.buf, "\t\t\treturn nil\n")
				fmt.Fprintf(&g.buf, "\t\t}\n")
			}
			fmt.Fprintf(&g.buf, "\t}\n")
		}
	}

	// Fallback: try each variant
	for i, vt := range variants {
		varName := fmt.Sprintf("vf%d", i)
		fmt.Fprintf(&g.buf, "\t{\n")
		fmt.Fprintf(&g.buf, "\t\tvar %s %s\n", varName, vt.wrapperName)
		fmt.Fprintf(&g.buf, "\t\tif err := json.Unmarshal(data, &%s); err == nil {\n", varName)
		fmt.Fprintf(&g.buf, "\t\t\t%s.variant = %s\n", recv, varName)
		fmt.Fprintf(&g.buf, "\t\t\treturn nil\n")
		fmt.Fprintf(&g.buf, "\t\t}\n")
		fmt.Fprintf(&g.buf, "\t}\n")
	}
	fmt.Fprintf(&g.buf, "\treturn fmt.Errorf(\"data does not match any variant of %s\")\n", goName)
	fmt.Fprintf(&g.buf, "}\n")

	// Accessors
	for _, vt := range variants {
		accessorName := vt.wrapperName
		if vt.isSlice {
			// For slice wrappers, strip parent prefix if present
			accessorName = strings.TrimPrefix(vt.wrapperName, goName)
		}
		fmt.Fprintf(&g.buf, "func (%s *%s) As%s() (%s, bool) {\n", recv, goName, accessorName, vt.wrapperName)
		fmt.Fprintf(&g.buf, "\tv, ok := %s.variant.(%s)\n", recv, vt.wrapperName)
		fmt.Fprintf(&g.buf, "\treturn v, ok\n")
		fmt.Fprintf(&g.buf, "}\n")
	}
	g.buf.WriteString("\n")

	// Constructors
	for _, vt := range variants {
		funcName := "New" + goName + vt.constructorID
		fmt.Fprintf(&g.buf, "// %s creates a %s holding a %s variant.\n", funcName, goName, vt.constructorID)
		fmt.Fprintf(&g.buf, "func %s(v %s) %s {\n", funcName, vt.rawType, goName)
		if vt.isSlice {
			fmt.Fprintf(&g.buf, "\treturn %s{variant: %s(v)}\n", goName, vt.wrapperName)
		} else {
			fmt.Fprintf(&g.buf, "\treturn %s{variant: v}\n", goName)
		}
		fmt.Fprintf(&g.buf, "}\n")
	}
	g.buf.WriteString("\n")
}

// resolveVariantRef extracts the $ref target from a variant schema,
// handling both direct $ref and allOf-wrapped $ref.
func resolveVariantRef(v *Schema) string {
	if v.Ref != "" {
		return v.Ref
	}
	if len(v.AllOf) == 1 && v.AllOf[0].Ref != "" {
		return v.AllOf[0].Ref
	}
	return ""
}

// variantRef holds a resolved variant reference and its schema for simple unions.
type variantRef struct {
	goType  string
	schema  *Schema
	isArray bool
}

// === Constants Generation ===

func (g *Generator) generateConstants() {
	if g.meta == nil {
		return
	}

	// Protocol version
	fmt.Fprintf(&g.buf, "const (\n")
	fmt.Fprintf(&g.buf, "\t// Current protocol version from metadata\n")
	fmt.Fprintf(&g.buf, "\tCurrentProtocolVersion int = %d\n", g.meta.Version)
	fmt.Fprintf(&g.buf, ")\n\n")

	// Agent methods
	if len(g.meta.AgentMethods) > 0 {
		g.generateMethodVar("AgentMethods", g.meta.AgentMethods)
	}

	// Client methods
	if len(g.meta.ClientMethods) > 0 {
		g.generateMethodVar("ClientMethods", g.meta.ClientMethods)
	}
}

func (g *Generator) generateMethodVar(varName string, methods map[string]string) {
	keys := sortedMapKeys(methods)

	// Struct type declaration
	fmt.Fprintf(&g.buf, "// %s method names\n", varName)
	fmt.Fprintf(&g.buf, "var %s = struct {\n", varName)
	for _, key := range keys {
		goFieldName := toTitleCase(key)
		fmt.Fprintf(&g.buf, "\t%s string\n", goFieldName)
	}
	fmt.Fprintf(&g.buf, "}{")

	// Values
	parts := make([]string, 0, len(keys))
	for _, key := range keys {
		goFieldName := toTitleCase(key)
		parts = append(parts, fmt.Sprintf("%s: %q", goFieldName, methods[key]))
	}
	g.buf.WriteString(strings.Join(parts, ", "))
	g.buf.WriteString("}\n\n")
}

// === Helpers ===

func isDispatchType(name string) bool {
	switch name {
	case "AgentNotification", "AgentRequest", "AgentResponse",
		"ClientNotification", "ClientRequest", "ClientResponse":
		return true
	}
	return false
}

// isExtPayloadType returns true for extension payload types that should be
// generated as json.RawMessage type aliases.
func isExtPayloadType(name string) bool {
	switch name {
	case "ExtNotification", "ExtRequest", "ExtResponse":
		return true
	}
	return false
}

func hasObjectType(s *Schema) bool {
	return s.Type.Contains("object")
}

func mergeAllOf(s *Schema) *Schema {
	merged := &Schema{
		Description: s.Description,
		Properties:  make(map[string]*Schema),
	}
	// Copy original properties
	for k, v := range s.Properties {
		merged.Properties[k] = v
	}
	merged.Required = append(merged.Required, s.Required...)

	for _, sub := range s.AllOf {
		if sub.Ref != "" {
			// Skip refs in merging - they become embedded types
			continue
		}
		for k, v := range sub.Properties {
			merged.Properties[k] = v
		}
		merged.Required = append(merged.Required, sub.Required...)
	}
	return merged
}

func sortedKeys(m map[string]*Schema) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedMapKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func strPtr(s string) *string {
	return &s
}
