// Code generated by cmd/generate; DO NOT EDIT.

package conn

import (
	"context"

	acp "github.com/eino-contrib/acp"
	"github.com/eino-contrib/acp/internal/jsonrpc"
)

// --- Outbound: Agent sends to Client (generated) ---

func (a *AgentConnection) UnstableElicitationComplete(ctx context.Context, params acp.CompleteElicitationNotification) error {
	return a.sender.SendNotification(ctx, acp.MethodClientUnstableElicitationComplete, params)
}

func (a *AgentConnection) UnstableCreateElicitation(ctx context.Context, params acp.CreateElicitationRequest) (acp.CreateElicitationResponse, error) {
	return jsonrpc.SendRequestTyped[acp.CreateElicitationResponse](a.sender, ctx, acp.MethodClientUnstableCreateElicitation, params)
}

func (a *AgentConnection) UnstableConnectMCP(ctx context.Context, params acp.ConnectMCPRequest) (acp.ConnectMCPResponse, error) {
	return jsonrpc.SendRequestTyped[acp.ConnectMCPResponse](a.sender, ctx, acp.MethodClientUnstableConnectMCP, params)
}

func (a *AgentConnection) UnstableDisconnectMCP(ctx context.Context, params acp.DisconnectMCPRequest) (acp.DisconnectMCPResponse, error) {
	return jsonrpc.SendRequestTyped[acp.DisconnectMCPResponse](a.sender, ctx, acp.MethodClientUnstableDisconnectMCP, params)
}

func (a *AgentConnection) UnstableMCPMessage(ctx context.Context, params acp.MessageMCPNotification) error {
	return a.sender.SendNotification(ctx, acp.MethodClientUnstableMCPMessage, params)
}

func (a *AgentConnection) RequestPermission(ctx context.Context, params acp.RequestPermissionRequest) (acp.RequestPermissionResponse, error) {
	return jsonrpc.SendRequestTyped[acp.RequestPermissionResponse](a.sender, ctx, acp.MethodClientRequestPermission, params)
}

func (a *AgentConnection) SessionUpdate(ctx context.Context, params acp.SessionNotification) error {
	return a.sender.SendNotification(ctx, acp.MethodClientSessionUpdate, params)
}
