// Code generated by cmd/generate; DO NOT EDIT.

package conn

import (
	"context"

	acp "github.com/eino-contrib/acp"
	"github.com/eino-contrib/acp/internal/jsonrpc"
)

// --- Outbound: Agent sends to Client (generated) ---

func (a *AgentConnection) UnstableElicitationComplete(ctx context.Context, params acp.CompleteElicitationNotification) error {
	return a.sender.SendNotification(ctx, acp.MethodClientUnstableElicitationComplete, params)
}

func (a *AgentConnection) UnstableCreateElicitation(ctx context.Context, params acp.CreateElicitationRequest) (acp.CreateElicitationResponse, error) {
	return jsonrpc.SendRequestTyped[acp.CreateElicitationResponse](a.sender, ctx, acp.MethodClientUnstableCreateElicitation, params)
}

func (a *AgentConnection) ReadTextFile(ctx context.Context, params acp.ReadTextFileRequest) (acp.ReadTextFileResponse, error) {
	return jsonrpc.SendRequestTyped[acp.ReadTextFileResponse](a.sender, ctx, acp.MethodClientReadTextFile, params)
}

func (a *AgentConnection) WriteTextFile(ctx context.Context, params acp.WriteTextFileRequest) (acp.WriteTextFileResponse, error) {
	return jsonrpc.SendRequestTyped[acp.WriteTextFileResponse](a.sender, ctx, acp.MethodClientWriteTextFile, params)
}

func (a *AgentConnection) RequestPermission(ctx context.Context, params acp.RequestPermissionRequest) (acp.RequestPermissionResponse, error) {
	return jsonrpc.SendRequestTyped[acp.RequestPermissionResponse](a.sender, ctx, acp.MethodClientRequestPermission, params)
}

func (a *AgentConnection) SessionUpdate(ctx context.Context, params acp.SessionNotification) error {
	return a.sender.SendNotification(ctx, acp.MethodClientSessionUpdate, params)
}

func (a *AgentConnection) CreateTerminal(ctx context.Context, params acp.CreateTerminalRequest) (acp.CreateTerminalResponse, error) {
	return jsonrpc.SendRequestTyped[acp.CreateTerminalResponse](a.sender, ctx, acp.MethodClientCreateTerminal, params)
}

func (a *AgentConnection) KillTerminal(ctx context.Context, params acp.KillTerminalRequest) (acp.KillTerminalResponse, error) {
	return jsonrpc.SendRequestTyped[acp.KillTerminalResponse](a.sender, ctx, acp.MethodClientKillTerminal, params)
}

func (a *AgentConnection) TerminalOutput(ctx context.Context, params acp.TerminalOutputRequest) (acp.TerminalOutputResponse, error) {
	return jsonrpc.SendRequestTyped[acp.TerminalOutputResponse](a.sender, ctx, acp.MethodClientTerminalOutput, params)
}

func (a *AgentConnection) ReleaseTerminal(ctx context.Context, params acp.ReleaseTerminalRequest) (acp.ReleaseTerminalResponse, error) {
	return jsonrpc.SendRequestTyped[acp.ReleaseTerminalResponse](a.sender, ctx, acp.MethodClientReleaseTerminal, params)
}

func (a *AgentConnection) WaitForTerminalExit(ctx context.Context, params acp.WaitForTerminalExitRequest) (acp.WaitForTerminalExitResponse, error) {
	return jsonrpc.SendRequestTyped[acp.WaitForTerminalExitResponse](a.sender, ctx, acp.MethodClientWaitForTerminalExit, params)
}
