// Code generated by cmd/generate; DO NOT EDIT.

package conn

import (
	"context"

	acp "github.com/eino-contrib/acp"
	"github.com/eino-contrib/acp/internal/jsonrpc"
)

// --- Outbound: Client sends to Agent (generated) ---

func (c *ClientConnection) Authenticate(ctx context.Context, params acp.AuthenticateRequest) (acp.AuthenticateResponse, error) {
	return jsonrpc.SendRequestTyped[acp.AuthenticateResponse](c.conn, ctx, acp.MethodAgentAuthenticate, params)
}

func (c *ClientConnection) DocumentDidChange(ctx context.Context, params acp.DidChangeDocumentNotification) error {
	return c.conn.SendNotification(ctx, acp.MethodAgentDocumentDidChange, params)
}

func (c *ClientConnection) DocumentDidClose(ctx context.Context, params acp.DidCloseDocumentNotification) error {
	return c.conn.SendNotification(ctx, acp.MethodAgentDocumentDidClose, params)
}

func (c *ClientConnection) DocumentDidFocus(ctx context.Context, params acp.DidFocusDocumentNotification) error {
	return c.conn.SendNotification(ctx, acp.MethodAgentDocumentDidFocus, params)
}

func (c *ClientConnection) DocumentDidOpen(ctx context.Context, params acp.DidOpenDocumentNotification) error {
	return c.conn.SendNotification(ctx, acp.MethodAgentDocumentDidOpen, params)
}

func (c *ClientConnection) DocumentDidSave(ctx context.Context, params acp.DidSaveDocumentNotification) error {
	return c.conn.SendNotification(ctx, acp.MethodAgentDocumentDidSave, params)
}

func (c *ClientConnection) Initialize(ctx context.Context, params acp.InitializeRequest) (acp.InitializeResponse, error) {
	return jsonrpc.SendRequestTyped[acp.InitializeResponse](c.conn, ctx, acp.MethodAgentInitialize, params)
}

func (c *ClientConnection) UnstableLogout(ctx context.Context, params acp.LogoutRequest) (acp.LogoutResponse, error) {
	return jsonrpc.SendRequestTyped[acp.LogoutResponse](c.conn, ctx, acp.MethodAgentUnstableLogout, params)
}

func (c *ClientConnection) NesAccept(ctx context.Context, params acp.AcceptNesNotification) error {
	return c.conn.SendNotification(ctx, acp.MethodAgentNesAccept, params)
}

func (c *ClientConnection) CloseNes(ctx context.Context, params acp.CloseNesRequest) (acp.CloseNesResponse, error) {
	return jsonrpc.SendRequestTyped[acp.CloseNesResponse](c.conn, ctx, acp.MethodAgentCloseNes, params)
}

func (c *ClientConnection) NesReject(ctx context.Context, params acp.RejectNesNotification) error {
	return c.conn.SendNotification(ctx, acp.MethodAgentNesReject, params)
}

func (c *ClientConnection) StartNes(ctx context.Context, params acp.StartNesRequest) (acp.StartNesResponse, error) {
	return jsonrpc.SendRequestTyped[acp.StartNesResponse](c.conn, ctx, acp.MethodAgentStartNes, params)
}

func (c *ClientConnection) SuggestNes(ctx context.Context, params acp.SuggestNesRequest) (acp.SuggestNesResponse, error) {
	return jsonrpc.SendRequestTyped[acp.SuggestNesResponse](c.conn, ctx, acp.MethodAgentSuggestNes, params)
}

func (c *ClientConnection) UnstableDisableProviders(ctx context.Context, params acp.DisableProvidersRequest) (acp.DisableProvidersResponse, error) {
	return jsonrpc.SendRequestTyped[acp.DisableProvidersResponse](c.conn, ctx, acp.MethodAgentUnstableDisableProviders, params)
}

func (c *ClientConnection) UnstableListProviders(ctx context.Context, params acp.ListProvidersRequest) (acp.ListProvidersResponse, error) {
	return jsonrpc.SendRequestTyped[acp.ListProvidersResponse](c.conn, ctx, acp.MethodAgentUnstableListProviders, params)
}

func (c *ClientConnection) UnstableSetProviders(ctx context.Context, params acp.SetProvidersRequest) (acp.SetProvidersResponse, error) {
	return jsonrpc.SendRequestTyped[acp.SetProvidersResponse](c.conn, ctx, acp.MethodAgentUnstableSetProviders, params)
}

func (c *ClientConnection) SessionCancel(ctx context.Context, params acp.CancelNotification) error {
	return c.conn.SendNotification(ctx, acp.MethodAgentSessionCancel, params)
}

func (c *ClientConnection) UnstableCloseSession(ctx context.Context, params acp.CloseSessionRequest) (acp.CloseSessionResponse, error) {
	return jsonrpc.SendRequestTyped[acp.CloseSessionResponse](c.conn, ctx, acp.MethodAgentUnstableCloseSession, params)
}

func (c *ClientConnection) UnstableForkSession(ctx context.Context, params acp.ForkSessionRequest) (acp.ForkSessionResponse, error) {
	return jsonrpc.SendRequestTyped[acp.ForkSessionResponse](c.conn, ctx, acp.MethodAgentUnstableForkSession, params)
}

func (c *ClientConnection) ListSessions(ctx context.Context, params acp.ListSessionsRequest) (acp.ListSessionsResponse, error) {
	return jsonrpc.SendRequestTyped[acp.ListSessionsResponse](c.conn, ctx, acp.MethodAgentListSessions, params)
}

// LoadSession sends a session/load request to the agent. When the underlying
// transport supports session listeners (e.g. Streamable HTTP), the
// ClientConnection automatically opens a GET SSE listener for the new
// session so that server-initiated messages are received without extra
// caller effort.
//
// The returned error reflects the RPC outcome only. Listener failures
// are reported via the handler registered with
// WithSessionListenerErrorHandler (or logged if none is set).
func (c *ClientConnection) LoadSession(ctx context.Context, params acp.LoadSessionRequest) (acp.LoadSessionResponse, error) {
	resp, err := jsonrpc.SendRequestTyped[acp.LoadSessionResponse](c.conn, ctx, acp.MethodAgentLoadSession, params)
	if err != nil {
		return resp, err
	}
	c.startSessionListener(ctx, string(params.SessionID))
	return resp, nil
}

// NewSession sends a session/new request to the agent. When the underlying
// transport supports session listeners (e.g. Streamable HTTP), the
// ClientConnection automatically opens a GET SSE listener for the new
// session so that server-initiated messages are received without extra
// caller effort.
//
// The returned error reflects the RPC outcome only. Listener failures
// are reported via the handler registered with
// WithSessionListenerErrorHandler (or logged if none is set).
func (c *ClientConnection) NewSession(ctx context.Context, params acp.NewSessionRequest) (acp.NewSessionResponse, error) {
	resp, err := jsonrpc.SendRequestTyped[acp.NewSessionResponse](c.conn, ctx, acp.MethodAgentNewSession, params)
	if err != nil {
		return resp, err
	}
	c.startSessionListener(ctx, string(resp.SessionID))
	return resp, nil
}

func (c *ClientConnection) Prompt(ctx context.Context, params acp.PromptRequest) (acp.PromptResponse, error) {
	return jsonrpc.SendRequestTyped[acp.PromptResponse](c.conn, ctx, acp.MethodAgentPrompt, params)
}

func (c *ClientConnection) UnstableResumeSession(ctx context.Context, params acp.ResumeSessionRequest) (acp.ResumeSessionResponse, error) {
	return jsonrpc.SendRequestTyped[acp.ResumeSessionResponse](c.conn, ctx, acp.MethodAgentUnstableResumeSession, params)
}

func (c *ClientConnection) SetSessionConfigOption(ctx context.Context, params acp.SetSessionConfigOptionRequest) (acp.SetSessionConfigOptionResponse, error) {
	return jsonrpc.SendRequestTyped[acp.SetSessionConfigOptionResponse](c.conn, ctx, acp.MethodAgentSetSessionConfigOption, params)
}

func (c *ClientConnection) SetSessionMode(ctx context.Context, params acp.SetSessionModeRequest) (acp.SetSessionModeResponse, error) {
	return jsonrpc.SendRequestTyped[acp.SetSessionModeResponse](c.conn, ctx, acp.MethodAgentSetSessionMode, params)
}

func (c *ClientConnection) UnstableSetSessionModel(ctx context.Context, params acp.SetSessionModelRequest) (acp.SetSessionModelResponse, error) {
	return jsonrpc.SendRequestTyped[acp.SetSessionModelResponse](c.conn, ctx, acp.MethodAgentUnstableSetSessionModel, params)
}
