// Code generated by cmd/generate; DO NOT EDIT.

package conn

import (
	"context"

	acp "github.com/eino-contrib/acp"
	"github.com/eino-contrib/acp/internal/connspi"
	"github.com/eino-contrib/acp/internal/jsonrpc"
)

// --- Outbound: Client sends to Agent (generated) ---

func (c *ClientConnection) Authenticate(ctx context.Context, params acp.AuthenticateRequest) (acp.AuthenticateResponse, error) {
	return jsonrpc.SendRequestTyped[acp.AuthenticateResponse](c.conn, ctx, acp.MethodAgentAuthenticate, params)
}

func (c *ClientConnection) Initialize(ctx context.Context, params acp.InitializeRequest) (acp.InitializeResponse, error) {
	return jsonrpc.SendRequestTyped[acp.InitializeResponse](c.conn, ctx, acp.MethodAgentInitialize, params)
}

func (c *ClientConnection) SessionCancel(ctx context.Context, params acp.CancelNotification) error {
	return c.conn.SendNotification(ctx, acp.MethodAgentSessionCancel, params)
}

func (c *ClientConnection) ListSessions(ctx context.Context, params acp.ListSessionsRequest) (acp.ListSessionsResponse, error) {
	return jsonrpc.SendRequestTyped[acp.ListSessionsResponse](c.conn, ctx, acp.MethodAgentListSessions, params)
}

// LoadSession sends a session/load request to the agent. When the underlying
// transport implements SessionListenerStarter (e.g. Streamable HTTP), it
// automatically opens a GET SSE listener for the new session so that
// server-initiated messages are received without extra caller effort.
//
// The returned error reflects the RPC outcome only. If the RPC
// succeeds but the local listener fails to start, the error is
// reported via the handler registered with
// WithSessionListenerErrorHandler (or logged if none is set) and the
// method returns (resp, nil). The session exists on the server, so
// callers must not retry as if the RPC had failed.
func (c *ClientConnection) LoadSession(ctx context.Context, params acp.LoadSessionRequest) (acp.LoadSessionResponse, error) {
	resp, err := jsonrpc.SendRequestTyped[acp.LoadSessionResponse](c.conn, ctx, acp.MethodAgentLoadSession, params)
	if err != nil {
		return resp, err
	}

	if hook := connspi.GetSessionListenerHook(c.transport); hook != nil && params.SessionID != "" {
		if lErr := hook.Start(ctx, string(params.SessionID)); lErr != nil {
			c.reportListenerError(string(params.SessionID), lErr)
		}
	}
	return resp, nil
}

// NewSession sends a session/new request to the agent. When the underlying
// transport implements SessionListenerStarter (e.g. Streamable HTTP), it
// automatically opens a GET SSE listener for the new session so that
// server-initiated messages are received without extra caller effort.
//
// The returned error reflects the RPC outcome only. If the RPC
// succeeds but the local listener fails to start, the error is
// reported via the handler registered with
// WithSessionListenerErrorHandler (or logged if none is set) and the
// method returns (resp, nil). The session exists on the server, so
// callers must not retry as if the RPC had failed.
func (c *ClientConnection) NewSession(ctx context.Context, params acp.NewSessionRequest) (acp.NewSessionResponse, error) {
	resp, err := jsonrpc.SendRequestTyped[acp.NewSessionResponse](c.conn, ctx, acp.MethodAgentNewSession, params)
	if err != nil {
		return resp, err
	}

	if hook := connspi.GetSessionListenerHook(c.transport); hook != nil && resp.SessionID != "" {
		if lErr := hook.Start(ctx, string(resp.SessionID)); lErr != nil {
			c.reportListenerError(string(resp.SessionID), lErr)
		}
	}
	return resp, nil
}

func (c *ClientConnection) Prompt(ctx context.Context, params acp.PromptRequest) (acp.PromptResponse, error) {
	return jsonrpc.SendRequestTyped[acp.PromptResponse](c.conn, ctx, acp.MethodAgentPrompt, params)
}

func (c *ClientConnection) SetSessionConfigOption(ctx context.Context, params acp.SetSessionConfigOptionRequest) (acp.SetSessionConfigOptionResponse, error) {
	return jsonrpc.SendRequestTyped[acp.SetSessionConfigOptionResponse](c.conn, ctx, acp.MethodAgentSetSessionConfigOption, params)
}

func (c *ClientConnection) SetSessionMode(ctx context.Context, params acp.SetSessionModeRequest) (acp.SetSessionModeResponse, error) {
	return jsonrpc.SendRequestTyped[acp.SetSessionModeResponse](c.conn, ctx, acp.MethodAgentSetSessionMode, params)
}
