// Code generated by cmd/generate; DO NOT EDIT.

package conn

import acp "github.com/eino-contrib/acp"

func newAgentRequestHandlers(agent acp.Agent, conn *AgentConnection) map[string]requestDispatcher {
	return map[string]requestDispatcher{
		acp.MethodAgentAuthenticate:           bindRequestHandler(agent.Authenticate),
		acp.MethodAgentInitialize:             bindRequestHandler(agent.Initialize),
		acp.MethodAgentListSessions:           bindRequestHandler(agent.ListSessions),
		acp.MethodAgentLoadSession:            bindRequestHandler(agent.LoadSession),
		acp.MethodAgentNewSession:             bindRequestHandler(agent.NewSession),
		acp.MethodAgentPrompt:                 bindRequestHandler(agent.Prompt),
		acp.MethodAgentSetSessionConfigOption: bindRequestHandler(agent.SetSessionConfigOption),
		acp.MethodAgentSetSessionMode:         bindRequestHandler(agent.SetSessionMode),
	}
}

func newAgentNotificationHandlers(conn *AgentConnection) map[string]notificationDispatcher {
	return map[string]notificationDispatcher{
		acp.MethodAgentSessionCancel: bindNotificationHandler("session/cancel notification", conn.agent.SessionCancel),
	}
}

func newClientRequestHandlers(client acp.Client) map[string]requestDispatcher {
	return map[string]requestDispatcher{
		acp.MethodClientReadTextFile:        bindRequestHandler(client.ReadTextFile),
		acp.MethodClientWriteTextFile:       bindRequestHandler(client.WriteTextFile),
		acp.MethodClientRequestPermission:   bindRequestHandler(client.RequestPermission),
		acp.MethodClientCreateTerminal:      bindRequestHandler(client.CreateTerminal),
		acp.MethodClientKillTerminal:        bindRequestHandler(client.KillTerminal),
		acp.MethodClientTerminalOutput:      bindRequestHandler(client.TerminalOutput),
		acp.MethodClientReleaseTerminal:     bindRequestHandler(client.ReleaseTerminal),
		acp.MethodClientWaitForTerminalExit: bindRequestHandler(client.WaitForTerminalExit),
	}
}

func newClientNotificationHandlers(client acp.Client) map[string]notificationDispatcher {
	return map[string]notificationDispatcher{
		acp.MethodClientSessionUpdate: bindNotificationHandler("session/update notification", client.SessionUpdate),
	}
}
